In [1]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.naive_bayes import MultinomialNB
import statsmodels.tools.tools as stattools
import jenkspy
from scipy import stats
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC


In [2]:
df = pd.read_csv('E:\\term8\\datamining\\HW\\project\\prepared_data.csv')
breaks = jenkspy.jenks_breaks(df['age'],nb_class = 5)
df['agebin'] = pd.cut(x = df['age'], bins = breaks, right = False, labels = [1,2,3,4,5])

breaks = jenkspy.jenks_breaks(df['bmi'],nb_class = 5)
df['bmibin'] = pd.cut(x = df['bmi'], bins = breaks, right = False, labels = [1,2,3,4,5])

breaks = jenkspy.jenks_breaks(df['avg_glucose_level'],nb_class = 5)
df['glubin'] = pd.cut(x = df['avg_glucose_level'], bins = breaks, right = False, labels = [1,2,3,4,5])
df = df.drop(columns = ['age', 'bmi', 'avg_glucose_level'])
df = pd.get_dummies(df, columns = ['agebin', 'bmibin', 'glubin'])

df_train, df_test = train_test_split(df, test_size = 0.2, random_state = 45)

In [3]:
temp = df_train[df['stroke'] == 1]
temp = temp.sample(n = len(df_train[df_train['stroke'] == 0]) - len(df_train[df_train['stroke'] == 1]),
                   replace = True)#20% of data: 800
df_train = pd.concat([df_train, temp])
y = df_train['stroke'].values
df_train = df_train.drop(columns = ['stroke'])
X = df_train.values
y_test = df_test['stroke'].values
df_test = df_test.drop(columns = ['stroke'])
X_test = df_test.values
%time nb_01 = MultinomialNB().fit(X, y)
%time Y_pred = nb_01.predict(X_test)
print(classification_report(y_test, Y_pred))
print(confusion_matrix(y_test, Y_pred, labels = [0, 1]))

Wall time: 8.31 ms
Wall time: 12 ms
              precision    recall  f1-score   support

           0       0.97      0.70      0.81       782
           1       0.15      0.74      0.25        57

    accuracy                           0.70       839
   macro avg       0.56      0.72      0.53       839
weighted avg       0.92      0.70      0.77       839

[[546 236]
 [ 15  42]]


E:\term6\Anaconda\setUp\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


In [4]:
df = pd.read_csv('E:\\term8\\datamining\\HW\\project\\prepared_data.csv')
df_train, df_test = train_test_split(df, test_size = 0.2, random_state = 45) 
temp = df_train[df['stroke'] == 1]
temp = temp.sample(n = len(df_train[df_train['stroke'] == 0]) - len(df_train[df_train['stroke'] == 1]),
                   replace = True)#20% of data: 800
df_train = pd.concat([df_train, temp])
X = df_train.values[:, 0:20]
y = df_train.values[:, 20]
X_test = df_test.values[:, 0:20]
y_test = df_test.values[:, 20]
%time clf = LogisticRegression(random_state=0).fit(X, y)
%time Y_pred = (clf.predict_proba(X_test)[:,1]>0.5)*1
print(classification_report(y_test, Y_pred))
print(confusion_matrix(y_test, Y_pred, labels = [0, 1]))

Wall time: 48.6 ms
Wall time: 14.7 ms
              precision    recall  f1-score   support

         0.0       0.97      0.73      0.83       782
         1.0       0.17      0.74      0.27        57

    accuracy                           0.73       839
   macro avg       0.57      0.73      0.55       839
weighted avg       0.92      0.73      0.80       839

[[571 211]
 [ 15  42]]


E:\term6\Anaconda\setUp\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until


In [5]:
%time clf = SVC(gamma='auto').fit(X, y)
%time Y_pred = clf.predict(X_test)
print(classification_report(y_test, Y_pred))
print(confusion_matrix(y_test, Y_pred, labels = [0, 1]))

Wall time: 3.2 s
Wall time: 699 ms
              precision    recall  f1-score   support

         0.0       0.97      0.72      0.82       782
         1.0       0.15      0.70      0.25        57

    accuracy                           0.72       839
   macro avg       0.56      0.71      0.54       839
weighted avg       0.91      0.72      0.79       839

[[560 222]
 [ 17  40]]


In [7]:
from sklearn.decomposition import PCA
pca_m = PCA(n_components=20).fit(X)
print(np.cumsum(pca_m.explained_variance_ratio_))

[0.27631845 0.4522046  0.56460633 0.64990563 0.73272904 0.7864999
 0.83591694 0.87230055 0.90591213 0.9377447  0.96466013 0.98538315
 0.9998912  0.99996078 1.         1.         1.         1.
 1.         1.        ]


In [14]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
X = df_train.values[:, 0:20]
y = df_train.values[:, 20]
X_test = df_test.values[:, 0:20]
y_test = df_test.values[:, 20]
pca_m = PCA(n_components=14).fit(X)
X = pca_m.transform(X)
X_test = pca_m.transform(X_test)
clf = SVC(gamma='auto')
%time clf.fit(X, y)
%time Y_pred = clf.predict(X_test)
print(classification_report(y_test, Y_pred))
print(confusion_matrix(y_test, Y_pred, labels = [0, 1]))

Wall time: 3.21 s
Wall time: 784 ms
              precision    recall  f1-score   support

         0.0       0.97      0.71      0.82       782
         1.0       0.15      0.67      0.24        57

    accuracy                           0.71       839
   macro avg       0.56      0.69      0.53       839
weighted avg       0.91      0.71      0.78       839

[[559 223]
 [ 19  38]]
